<a href="https://colab.research.google.com/github/mostafadentist/python-ipynb/blob/main/Transportation_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Supply from factories
supply = [20, 30, 25]

# Demand at warehouses
demand = [10, 10, 15, 40]

# Cost matrix
cost = np.array([[8, 6, 10, 9],
                 [9, 12, 13, 7],
                 [14, 9, 16, 5]])

In [2]:
def northwest_corner(supply, demand):
    supply = supply.copy()
    demand = demand.copy()
    m, n = len(supply), len(demand)
    allocation = np.zeros((m,n))
    i = j = 0
    while i < m and j < n:
        qty = min(supply[i], demand[j])
        allocation[i,j] = qty
        supply[i] -= qty
        demand[j] -= qty
        if supply[i] == 0:
            i += 1
        else:
            j += 1
    return allocation

alloc = northwest_corner(supply, demand)
print("Northwest Corner Allocation:\n", alloc)
print("Total Cost =", np.sum(alloc * cost))

Northwest Corner Allocation:
 [[10. 10.  0.  0.]
 [ 0.  0. 15. 15.]
 [ 0.  0.  0. 25.]]
Total Cost = 565.0
