![sslogo](https://github.com/stratascratch/stratascratch.github.io/raw/master/assets/sslogo.jpg)

# Concatenating and Merging Dataframes

- https://pandas.pydata.org/pandas-docs/stable/merging.html

In this lesson we will use 3 datasets provided by Yelp.
* yelp_business
* yelp_business_hours
* yelp_reviews

In [0]:
import pandas as pd
import numpy  as np
import psycopg2 as ps

In [0]:
# Connect to database
host_name = 'db-strata.stratascratch.com'
dbname = 'db_strata'
port = '5432'
# TODO Write your username and database password in the following two variables
user_name = '' #enter username
pwd = '' #enter your database password found in the profile tab in Strata Scratch

try:
    conn = ps.connect(host=host_name,database=dbname,user=user_name,password=pwd,port=port)
except ps.OperationalError as e:
    raise e
else:
    print('Connected!')

Connected!


In [0]:
# Get the data we will use for this exercise

def get_dataset(dataset_name):
    #Write SQL below to pull datasets 
    cur = conn.cursor()
    cur.execute(""" 
                SELECT *  FROM datasets.{0}; 
                """.format(dataset_name))
    data = cur.fetchall()
    colnames = [desc[0] for desc in cur.description] 
    conn.commit()

    #create the pandas dataframe
    dataframe = pd.DataFrame(data, columns=colnames)

    #close the connection
    cur.close()
    
    return dataframe

yelp_business = get_dataset("yelp_business")
yelp_hours    = get_dataset("yelp_business_hours")
yelp_reviews  = get_dataset("yelp_reviews")

# a little bit preprocessing
yelp_reviews['business_name'] = yelp_reviews['business_name'].apply(lambda x: '"{0}"'.format(x))

In [0]:
yelp_business.head()

business_id                        name neighborhood  \
0  FYWN1wneV18bWNgQjJ2GNg          "Dental by Design"         None   
1  He-G7vWjzVUysIKrfNbPUQ       "Stephen Szabo Salon"         None   
2  KQPW8lFf1y5BT2MxiSZ3QA     "Western Motor Vehicle"         None   
3  8DShNS-LuFqpEWIp0HxijA          "Sports Authority"         None   
4  PfOCPjBrlQAnz__NXj9h_w  "Brick House Tavern + Tap"         None   

                            address            city state postal_code  \
0        "4855 E Warner Rd, Ste B9"       Ahwatukee    AZ       85044   
1              "3101 Washington Rd"        McMurray    PA       15317   
2          "6025 N 27th Ave, Ste 1"         Phoenix    AZ       85017   
3  "5000 Arizona Mills Cr, Ste 435"           Tempe    AZ       85282   
4                    "581 Howe Ave"  Cuyahoga Falls    OH       44221   

    latitude   longitude  stars  review_count  is_open  \
0  33.330690 -111.978599    4.0            22        1   
1  40.291685  -80.104900    3.0            11        1   
2  33.524903 -112.115310    1.5            18        1   
3  33.383147 -111.964725    3.0             9        0   
4  41.119535  -81.475690    3.5           116        1   

                                          categories  
0  Dentists;General Dentistry;Health & Medical;Or...  
1  Hair Stylists;Hair Salons;Men's Hair Salons;Bl...  
2  Departments of Motor Vehicles;Public Services ...  
3                            Sporting Goods;Shopping  
4  American (New);Nightlife;Bars;Sandwiches;Ameri...

In [0]:
yelp_hours.head()

business_id     monday    tuesday  wednesday   thursday  \
0  FYWN1wneV18bWNgQjJ2GNg  7:30-17:0  7:30-17:0  7:30-17:0  7:30-17:0   
1  He-G7vWjzVUysIKrfNbPUQ   9:0-20:0   9:0-20:0   9:0-20:0   9:0-20:0   
2  KQPW8lFf1y5BT2MxiSZ3QA       None       None       None       None   
3  8DShNS-LuFqpEWIp0HxijA  10:0-21:0  10:0-21:0  10:0-21:0  10:0-21:0   
4  PfOCPjBrlQAnz__NXj9h_w   11:0-1:0   11:0-1:0   11:0-1:0   11:0-1:0   

      friday   saturday     sunday  
0  7:30-17:0       None       None  
1   9:0-16:0   8:0-16:0       None  
2       None       None       None  
3  10:0-21:0  10:0-21:0  11:0-19:0  
4   11:0-1:0   11:0-2:0   11:0-0:0

In [0]:
yelp_reviews.head()

business_name               review_id  \
0  "Thai Pan Fresh Exotic Cuisine"  0ESSqLfOae77muWTv_zUqA   
1                     "Salon Lola"  VyAKIaj_Rmsf_ZCHcGJyUw   
2         "Chipotle Mexican Grill"  DusrkpkTGPGkqK13xO1TZg   
3                     "Sam's Deli"  A5FL-YYXnr2hnvXQbgkkrQ   
4                          "Petco"  SzhIWfzLHUZfiAaVTtKHxw   

                  user_id stars review_date  \
0  r-t7IiTSD0QZdt8lOUCqeQ     3  2011-02-11   
1  SS85hfTApRnbTPcJadra8A     5  2010-05-30   
2  xAVu2pZ6nIvkdHh8vGs84Q     3  2011-11-26   
3  Xuvj2Fq6c3mCmplVG7h21w     4  2013-10-10   
4  jHH_UDpCnF-YTnveyoMTIA     1  2012-09-02   

                                         review_text  funny  useful  cool  
0  Lately i have been feeling homesick for asian ...      1       1     1  
1  I love Marilo!  She understands my hair type a...      0       0     0  
2  Standard Chipotle fare - consistently good; no...      0       0     0  
3         Very good prices with quality ingredients.      0       0     0  
4  I went to this Petco a few times and was a bit...      0       1     0

## Concatenatations

### What are they?

If you think of your dataframes as rectangles in a 2D coordinate system concatenating means taking two or more rectangles and putting them next to each other so they touch on the concatenating axis.

We will use two types of concatenations, numpy and pandas.

The pandas version builds upon the numpy basics by incorporating ideas like indexes and keys but the main idea is the same.

The functions we will learn first are
- [np.hstack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dstack.html)
- [np.vstack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html)

In numpy lingo stack means concatenate. Pandas uses the terminology concat.

In [0]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
array2 = np.array([[1, 0, 1], [1, 1, 1], [0, 1, 0]])

array2

array([[1, 0, 1],
       [1, 1, 1],
       [0, 1, 0]])

In [0]:
# hstack stands for horizontal stack (stack axis is parallel to Y axis)
print(np.hstack([array1, array2]))

[[1 2 3 1 0 1]
 [4 5 6 1 1 1]
 [7 8 9 0 1 0]]


In [0]:
# vstack stands for vertical stack (stack axis is parallel to X axis)
print(np.vstack([array1, array2]))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 0 1]
 [1 1 1]
 [0 1 0]]


Both stacking functions take a list of nd-arrays and return a single nd-array.

Here is another example this time using 1d-arrays and stacking to build a 2d-array.

In [0]:
row1 = np.array([3, -3, 3])
row2 = np.array([6, -9, 27])
row3 = np.array([9, -27, 81])

np.vstack([row1, row2, row3])

array([[  3,  -3,   3],
       [  6,  -9,  27],
       [  9, -27,  81]])

### Concatenating dataframes

Because dataframes are a bit more than 2d-arrays we can concatenate them as well.

We can use the numpy functions `hstack` and `vstack` but it is recommended to use `pd.concatenate` because of indexes.
- https://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html

There are a lot of arguments but as always let's start small.

In [0]:
df1 = pd.DataFrame({
    "name": ["A", "B", "C", "D"],
    "age": [22, 18, 46, 81],
}, index=[0, 1, 2, 3])

df2 = pd.DataFrame({
    "name": ["G", "H", "I"],
    "age": [10, 20, 30]
}, index=[4, 5, 6])

print(df1)
print(df2)

  name  age
0    A   22
1    B   18
2    C   46
3    D   81
  name  age
4    G   10
5    H   20
6    I   30


In [0]:
# simplest possible use case will do a vstack
pd.concat([df1, df2])

name  age
0    A   22
1    B   18
2    C   46
3    D   81
4    G   10
5    H   20
6    I   30

In [0]:
# Passing axis=1 will do hstack
pd.concat([df1, df2], axis=1)

name   age name   age
0    A  22.0  NaN   NaN
1    B  18.0  NaN   NaN
2    C  46.0  NaN   NaN
3    D  81.0  NaN   NaN
4  NaN   NaN    G  10.0
5  NaN   NaN    H  20.0
6  NaN   NaN    I  30.0

**Quick remark: np.hstack and np.vstack will throw an error if shapes do not match, pd.concatenate will extend the dataframes with null values depending on the join parameter.**

Passing the keys property will make the resulting dataframe have a [MultiIndex](https://pandas.pydata.org/pandas-docs/stable/advanced.html#advanced-hierarchical) whose first level is the value which describes the dataframe.

In [0]:
pd.concat([df1, df2], keys=['df_left', 'df_right'])

name  age
df_left  0    A   22
         1    B   18
         2    C   46
         3    D   81
df_right 4    G   10
         5    H   20
         6    I   30

When you concatenate on axis where the shapes do not match you should set the join paramater to one of its two values:
- "inner" which means take the intersection over the index axis of the dataframes being concatenated
- "outer" which means take the union over the index axis of the dataframes being concatenated

The default value is "outer" which gives the behaviour as described by the quick remark above.

In [0]:
pd.concat([df1, df2], axis=1, join='inner')

Empty DataFrame
Columns: [name, age, name, age]
Index: []

In [0]:
pd.concat([df1, df2], axis=1, join='outer')

name   age name   age
0    A  22.0  NaN   NaN
1    B  18.0  NaN   NaN
2    C  46.0  NaN   NaN
3    D  81.0  NaN   NaN
4  NaN   NaN    G  10.0
5  NaN   NaN    H  20.0
6  NaN   NaN    I  30.0

The final important parameter to talk about is `ignore_index`.

If you pass `ignore_index=True` pandas will concatenate the dataframes without looking at the index.

Generally you do not need to use this but if you concatenate dataframes with different index types you will need this.

The [append](https://pandas.pydata.org/pandas-docs/stable/merging.html#concatenating-using-append) method is similar to concat in the sense that the following holds true

`df1.append(df2) = pd.concat([df1, df2])`

You should prefer concat almost always because it is more general.

#### Practical example 

List comprehension and pd.concat to get 1, 3, 5 stared rows from yelp_reviews dataset.

In [0]:
pd.concat([
           yelp_reviews[yelp_reviews.stars == stars] 
           for stars in ['1', '3', '5']
          ])

# another solution without using pd.concat
# yelp_reviews[yelp_reviews.stars.isin(['1', '3', '5'])]

business_name  \
4                                                "Petco"   
12                          "Canteen Modern Tequila Bar"   
60                        "Fairmont Scottsdale Princess"   
71                   "Gordon Biersch Brewery Restaurant"   
79                                       "Golden Buddha"   
93                                   "A Better Grooming"   
104                           "Paradise Bakery and Cafe"   
108                                     "Pork on a Fork"   
142                            "Meineke Car Care Center"   
144                                   "Joe's Crab Shack"   
148                                  "Round Table Pizza"   
196                                      "Market Bistro"   
219                                         "Mimis Cafe"   
250                                          "Gypsy Bar"   
251             "GoWireless - Verizon Wireless Retailer"   
252                                       "Barrio Queen"   
270                                     "Geisha A Go Go"   
287            "Pei Wei - Asian Inspired. Freshly Made."   
318                                     "Squash Blossom"   
326                              "Dick's Sporting Goods"   
343                                    "Trillium Papago"   
354                          "Sonora Quest Laboratories"   
358                 "Ling & Louie's Asian Bar and Grill"   
389                                          "McDonalds"   
415                                      "Estrella Taxi"   
430                                            "Da Vˆng"   
439                                           "PastaBAR"   
444                              "Arrivederci Trattoria"   
455                     "Villa Peru Peruvian Restaurant"   
492                                    "Cookiez On Mill"   
...                                                  ...   
16310                                     "Jimmy John's"   
16311                                        "Binkley's"   
16314                 "Cactus Aquatics & Fitness Center"   
16318                 "Fresh & Easy Neighborhood Market"   
16319  "Helping Hands - Home & Office Cleaning Services"   
16322                         "Changing Hands Bookstore"   
16323                                "Crescent Ballroom"   
16329                                   "The Greek Pita"   
16335                                "Casey Jones Grill"   
16337                                   "Tortas Paquime"   
16339                "AMC Dine-in Theatres Esplanade 14"   
16343                                   "Rainbow Donuts"   
16344                                       "Kitchen 56"   
16347                                           "Costco"   
16353                                 "New India Bazaar"   
16355                              "Old Town Scottsdale"   
16359                            "Original ChopShop Co."   
16360               "La Bocca Urban Pizzeria + Wine Bar"   
16365                        "Red Robin Gourmet Burgers"   
16366                             "Rehab Burger Therapy"   
16368                            "Nobuo At Teeter House"   
16371                              "Superstition Coffee"   
16373                          "VinciTorio's Restaurant"   
16374                                   "Sweet Republic"   
16377                                  "Carlsbad Tavern"   
16384                              "Cafeteria on Thomas"   
16386                    "Green New American Vegetarian"   
16387                                 "Taquitos Jalisco"   
16388                              "Grimaldi's Pizzeria"   
16389           "The Main Ingredient Ale House And CafŽ"   

                    review_id                 user_id stars review_date  \
4      SzhIWfzLHUZfiAaVTtKHxw  jHH_UDpCnF-YTnveyoMTIA     1  2012-09-02   
12     qnpnnZ_JrOLsIdtn5aB9Hw  _4lqpCYCqOQzbB6xQGGhrQ     1  2010-10-14   
60     pmXF1ajhiMietpARXXX-iw  PBdpLP3yMHV79Y7EjuBY4g     1  2010-11-25   
71     avwF0OJFhNxu-s9

## Merges and Joins
- https://pandas.pydata.org/pandas-docs/stable/merging.html#database-style-dataframe-joining-merging

pandas can perform relational joins in memory using the `merge` method which we discuss for the remainder of this lesson.

Each dataframe also has a `join` method but the following holds true (for details see the docs)

`df1.join(df2) = pd.merge(df1, df2, left_index=True, right_index=True, how="left")`

By default merge does an inner join, while [`pd.DataFrame.join`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.join.html) does a left join but these are configurable with the how parameter.

The most imporant parameter of `pd.merge` is the choice of join type in the parameter called `how`.
- "inner" which corresponds to INNER JOIN in SQL
- "outer" which corresponds to FULL OUTER JOIN in SQL
- "left" which corresponds to LEFT OUTER JOIN in SQL
- "right" which corresponds to RIGHT OUTER JOIN in SQL

Second most important choice is what to join on.
- Column or a list of columns (e.g. ["bussiness_id"])
- Index 

You can choose either of them for both left and right(e.g. columns for left and index for right, or columns for both or indices for both)

*By default merge will work with indexes*

#### Example 1 of merge function

An example of inner join between yelp_business and yelp_hours on business_id column.

In [0]:
pd.merge(yelp_business, yelp_hours, how="inner", left_on=["business_id"], right_on=["business_id"])

business_id  \
0       FYWN1wneV18bWNgQjJ2GNg   
1       He-G7vWjzVUysIKrfNbPUQ   
2       KQPW8lFf1y5BT2MxiSZ3QA   
3       8DShNS-LuFqpEWIp0HxijA   
4       PfOCPjBrlQAnz__NXj9h_w   
5       o9eMRCWt5PkpLDE0gOPtcQ   
6       kCoE3jvEtg6UVz5SOD3GVw   
7       OD2hnuuTJI9uotcKycxg1A   
8       EsMcGiZaQuG1OOvL9iUFug   
9       TGWhGNusxyMaA4kQVBNeew   
10      XOSRcvtaKc_Q5H1SAzN20A   
11      Y0eMNa5C-YU1RQOZf9XvVA   
12      xcgFnd-MwkZeO5G2HQ0gAQ   
13      NmZtoE3v8RdSJEczYbMT9g   
14      fNMVV_ZX7CJSDWQGdOM8Nw   
15      l09JfMeQ6ynYs5MCJtrcmQ   
16      IQSlT5jGE6CCDhSG0zG3xg   
17      b2I2DXtZVnpUMCXp1JON7A   
18      0FMKDOU8TJT1x87OKYGDTg   
19      Gu-xs3NIQTj3Mj2xYoN2aw   
20      lHYiCS-y8AFjUitv6MGpxg   
21      94KziT6DQ9XlBET3WzIv_w   
22      7YIy1tXOor9VCwvaSjuBHg   
23      PMH4oUa-bWELKogdtkWewg   
24      VSGcuYDV3q-AAZ9ZPq4fBQ   
25      1K4qrnfyzKzGgJPBEcJaNQ   
26      VBHEsoXQb2AQ76J9l8h1uQ   
27      AtdXq_gu9NTE5rx4ct_dGg   
28      Dj0S-Oe4ytRJzMGUPgYUkw   
29      gAy4LYpsScrj8POnCW6btQ   
...                        ...   
174537  z9BQubTnhhZd0iTJ-THbxg   
174538  axvE68Q_osdFijj1a21Omw   
174539  swjz4q8gI79Ndg4APuHEUA   
174540  g0uFTFdKGarWEPb9gHlmag   
174541  PfSNuUa53A-N5rY1kRshmA   
174542  BhcpdT3W7YeyFeVAWPolkQ   
174543  SvW3WsatQWvR8c1iwAD_QA   
174544  nGjEV4bn0DPk8bcb0C6Aig   
174545  pUhU5ohYv65g8B47dTXAKA   
174546  sH9WsMj8sNTTSAUWv4UEEg   
174547  OMXqIZdvhDlrXlkpR34diQ   
174548  FxtrmM1a_0jcNnxiEF_Emg   
174549  iR1CIWFZOlfndjXn9fHflQ   
174550  R2oTFgwyurdx8fmZh7uAGg   
174551  6jzWUo0HAT3hNgBH-zHtYg   
174552  9ouC6BpmjFpLfHeQnLQqng   
174553  JnhuORtEQOW8XkVXB3l2tQ   
174554  vewqpBniDWKH4R05hxQwUQ   
174555  yJH_gq99aEj8xtyBaAQH8Q   
174556  n9a-3YhibkMDUEgncIivHg   
174557  fp97iuseEoP7SGv74lSnhQ   
174558  UdEmYOnk2iJDY9lpEPAlJQ   
174559  N-ujj4Xsq7Qg9A1fDGkUmA   
174560  fBUoQ3WCyQX9sMWteZfI3w   
174561  kLFm_kehXNZkUc1oa2-Eaw   
174562  ALV5R8NkZ1KGOZeuZl3u0A   
174563  gRGalHVu6BcaUDIAGVW_xQ   
174564  XXvZBIHoJBU5d6-a-oyMWQ   
174565  lNpPGgM96nPIYM1shxciHg   
174566  viKaP26BcHU6cLx8sf4gKg   

                                                     name  \
0                                      "Dental by Design"   
1                                   "Stephen Szabo Salon"   
2                                 "Western Motor Vehicle"   
3                                      "Sports Authority"   
4                              "Brick House Tavern + Tap"   
5                                               "Messina"   
6                                            "BDJ Realty"   
7                                           "Soccer Zone"   
8                                      "Any Given Sundae"   
9                                 "Detailing Gone Mobile"   
10                                    "East Coast Coffee"   
11                               "CubeSmart Self Storage"   
12                                "T & T Bakery and Cafe"   
13                                 "Complete Dental Care"   
14                           "Showmars Government Center"   
15                                       "Alize Catering"   
16                                       "T & Y Nail Spa"   
17                              "Meineke Car Care Center"   
18                                 "Senior's Barber Shop"   
19                            "Maxim Bakery & Restaurant"   
20                                            "Starbucks"   
21                                                  "Fye"   
22      "TSA Checkpoint T-4 A - Phoenix Sky Harbor Int...   
23                                     "GoodLife Fitness"   
24                                          "Sportster's"   
25                               "Chula Taberna Mexicana"   
26                                    "Alfredo's Jewelry"   
27                                            "DAVIDsTEA"   
28                                         "Panera Bread"   
29                                           "Toast Cafe"   
...                

#### Example 2 of merge function

If the join columns are named the same in both dataframes you can use the `on` parameter and write less code.

The result of this join and the join right above is the same.

In [0]:
pd.merge(yelp_business, yelp_hours, how="inner", on=["business_id"])

business_id  \
0       FYWN1wneV18bWNgQjJ2GNg   
1       He-G7vWjzVUysIKrfNbPUQ   
2       KQPW8lFf1y5BT2MxiSZ3QA   
3       8DShNS-LuFqpEWIp0HxijA   
4       PfOCPjBrlQAnz__NXj9h_w   
5       o9eMRCWt5PkpLDE0gOPtcQ   
6       kCoE3jvEtg6UVz5SOD3GVw   
7       OD2hnuuTJI9uotcKycxg1A   
8       EsMcGiZaQuG1OOvL9iUFug   
9       TGWhGNusxyMaA4kQVBNeew   
10      XOSRcvtaKc_Q5H1SAzN20A   
11      Y0eMNa5C-YU1RQOZf9XvVA   
12      xcgFnd-MwkZeO5G2HQ0gAQ   
13      NmZtoE3v8RdSJEczYbMT9g   
14      fNMVV_ZX7CJSDWQGdOM8Nw   
15      l09JfMeQ6ynYs5MCJtrcmQ   
16      IQSlT5jGE6CCDhSG0zG3xg   
17      b2I2DXtZVnpUMCXp1JON7A   
18      0FMKDOU8TJT1x87OKYGDTg   
19      Gu-xs3NIQTj3Mj2xYoN2aw   
20      lHYiCS-y8AFjUitv6MGpxg   
21      94KziT6DQ9XlBET3WzIv_w   
22      7YIy1tXOor9VCwvaSjuBHg   
23      PMH4oUa-bWELKogdtkWewg   
24      VSGcuYDV3q-AAZ9ZPq4fBQ   
25      1K4qrnfyzKzGgJPBEcJaNQ   
26      VBHEsoXQb2AQ76J9l8h1uQ   
27      AtdXq_gu9NTE5rx4ct_dGg   
28      Dj0S-Oe4ytRJzMGUPgYUkw   
29      gAy4LYpsScrj8POnCW6btQ   
...                        ...   
174537  z9BQubTnhhZd0iTJ-THbxg   
174538  axvE68Q_osdFijj1a21Omw   
174539  swjz4q8gI79Ndg4APuHEUA   
174540  g0uFTFdKGarWEPb9gHlmag   
174541  PfSNuUa53A-N5rY1kRshmA   
174542  BhcpdT3W7YeyFeVAWPolkQ   
174543  SvW3WsatQWvR8c1iwAD_QA   
174544  nGjEV4bn0DPk8bcb0C6Aig   
174545  pUhU5ohYv65g8B47dTXAKA   
174546  sH9WsMj8sNTTSAUWv4UEEg   
174547  OMXqIZdvhDlrXlkpR34diQ   
174548  FxtrmM1a_0jcNnxiEF_Emg   
174549  iR1CIWFZOlfndjXn9fHflQ   
174550  R2oTFgwyurdx8fmZh7uAGg   
174551  6jzWUo0HAT3hNgBH-zHtYg   
174552  9ouC6BpmjFpLfHeQnLQqng   
174553  JnhuORtEQOW8XkVXB3l2tQ   
174554  vewqpBniDWKH4R05hxQwUQ   
174555  yJH_gq99aEj8xtyBaAQH8Q   
174556  n9a-3YhibkMDUEgncIivHg   
174557  fp97iuseEoP7SGv74lSnhQ   
174558  UdEmYOnk2iJDY9lpEPAlJQ   
174559  N-ujj4Xsq7Qg9A1fDGkUmA   
174560  fBUoQ3WCyQX9sMWteZfI3w   
174561  kLFm_kehXNZkUc1oa2-Eaw   
174562  ALV5R8NkZ1KGOZeuZl3u0A   
174563  gRGalHVu6BcaUDIAGVW_xQ   
174564  XXvZBIHoJBU5d6-a-oyMWQ   
174565  lNpPGgM96nPIYM1shxciHg   
174566  viKaP26BcHU6cLx8sf4gKg   

                                                     name  \
0                                      "Dental by Design"   
1                                   "Stephen Szabo Salon"   
2                                 "Western Motor Vehicle"   
3                                      "Sports Authority"   
4                              "Brick House Tavern + Tap"   
5                                               "Messina"   
6                                            "BDJ Realty"   
7                                           "Soccer Zone"   
8                                      "Any Given Sundae"   
9                                 "Detailing Gone Mobile"   
10                                    "East Coast Coffee"   
11                               "CubeSmart Self Storage"   
12                                "T & T Bakery and Cafe"   
13                                 "Complete Dental Care"   
14                           "Showmars Government Center"   
15                                       "Alize Catering"   
16                                       "T & Y Nail Spa"   
17                              "Meineke Car Care Center"   
18                                 "Senior's Barber Shop"   
19                            "Maxim Bakery & Restaurant"   
20                                            "Starbucks"   
21                                                  "Fye"   
22      "TSA Checkpoint T-4 A - Phoenix Sky Harbor Int...   
23                                     "GoodLife Fitness"   
24                                          "Sportster's"   
25                               "Chula Taberna Mexicana"   
26                                    "Alfredo's Jewelry"   
27                                            "DAVIDsTEA"   
28                                         "Panera Bread"   
29                                           "Toast Cafe"   
...                

#### Example 3 of merge function

You can also join on indexes.

First we must make the bussiness_id column the index in both dataframes (see [set_index](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.set_index.html) for more info).

Then we join on index.

In [0]:
pd.merge(left=yelp_business.set_index(["business_id"]),
         right=yelp_hours.set_index(["business_id"]),
         how="inner",
         left_index=True,
         right_index=True)

name  \
business_id                                                                 
FYWN1wneV18bWNgQjJ2GNg                                 "Dental by Design"   
He-G7vWjzVUysIKrfNbPUQ                              "Stephen Szabo Salon"   
KQPW8lFf1y5BT2MxiSZ3QA                            "Western Motor Vehicle"   
8DShNS-LuFqpEWIp0HxijA                                 "Sports Authority"   
PfOCPjBrlQAnz__NXj9h_w                         "Brick House Tavern + Tap"   
o9eMRCWt5PkpLDE0gOPtcQ                                          "Messina"   
kCoE3jvEtg6UVz5SOD3GVw                                       "BDJ Realty"   
OD2hnuuTJI9uotcKycxg1A                                      "Soccer Zone"   
EsMcGiZaQuG1OOvL9iUFug                                 "Any Given Sundae"   
TGWhGNusxyMaA4kQVBNeew                            "Detailing Gone Mobile"   
XOSRcvtaKc_Q5H1SAzN20A                                "East Coast Coffee"   
Y0eMNa5C-YU1RQOZf9XvVA                           "CubeSmart Self Storage"   
xcgFnd-MwkZeO5G2HQ0gAQ                            "T & T Bakery and Cafe"   
NmZtoE3v8RdSJEczYbMT9g                             "Complete Dental Care"   
fNMVV_ZX7CJSDWQGdOM8Nw                       "Showmars Government Center"   
l09JfMeQ6ynYs5MCJtrcmQ                                   "Alize Catering"   
IQSlT5jGE6CCDhSG0zG3xg                                   "T & Y Nail Spa"   
b2I2DXtZVnpUMCXp1JON7A                          "Meineke Car Care Center"   
0FMKDOU8TJT1x87OKYGDTg                             "Senior's Barber Shop"   
Gu-xs3NIQTj3Mj2xYoN2aw                        "Maxim Bakery & Restaurant"   
lHYiCS-y8AFjUitv6MGpxg                                        "Starbucks"   
94KziT6DQ9XlBET3WzIv_w                                              "Fye"   
7YIy1tXOor9VCwvaSjuBHg  "TSA Checkpoint T-4 A - Phoenix Sky Harbor Int...   
PMH4oUa-bWELKogdtkWewg                                 "GoodLife Fitness"   
VSGcuYDV3q-AAZ9ZPq4fBQ                                      "Sportster's"   
1K4qrnfyzKzGgJPBEcJaNQ                           "Chula Taberna Mexicana"   
VBHEsoXQb2AQ76J9l8h1uQ                                "Alfredo's Jewelry"   
AtdXq_gu9NTE5rx4ct_dGg                                        "DAVIDsTEA"   
Dj0S-Oe4ytRJzMGUPgYUkw                                     "Panera Bread"   
gAy4LYpsScrj8POnCW6btQ                                       "Toast Cafe"   
...                                                                   ...   
z9BQubTnhhZd0iTJ-THbxg                                           "Isobar"   
axvE68Q_osdFijj1a21Omw                                   "Flair Cleaners"   
swjz4q8gI79Ndg4APuHEUA                   "Stonegate Real Estate Services"   
g0uFTFdKGarWEPb9gHlmag                    "Tanner Materials Tile & Stone"   
PfSNuUa53A-N5rY1kRshmA                              "Duquesne University"   
BhcpdT3W7YeyFeVAWPolkQ                             "Goodyear Endodontics"   
SvW3WsatQWvR8c1iwAD_QA                                 "Urban House Cafe"   
nGjEV4bn0DPk8bcb0C6Aig                      "Sweet Serendipity Bake Shop"   
pUhU5ohYv65g8B47dTXAKA                                        "Starbucks"   
sH9WsMj8sNTTSAUWv4UEEg                                     "Sprint Store"   
OMXqIZdvhDlrXlkpR34diQ                             "Swim Platforms, Inc."   
FxtrmM1a_0jcNnxiEF_Emg                                        "Badgarten"   
iR1CIWFZOlfndjXn9fHflQ                                 "Last Drop Tavern"   
R2oTFgwyurdx8fmZh7uAGg                                        "Hot Topic"   
6jzWUo0HAT3hNgBH-zHtYg                                           "Target"   
9ouC6BpmjFpLfHeQnLQqng                             "9 Dragons Fight Shop"   
JnhuORtEQOW8XkVXB3l2tQ                                              "CVS"   
vewqpBniDWKH4R05hxQwUQ                                      "Eos Fitness"   
yJH_gq99aEj8xtyBaAQH8Q                                       "Otto Onkel"   
n9a-3YhibkMDUEgncIivHg                                       "L'O

#### The suffixes parameter

The `suffixes` parameter is a tuple made of two strings.
- The first element of this tuple is the suffix for columns from the left dataframe
- The second element of this tuple is the suffix for columns from the right dataframe

The suffix is applied only to columns which have identical names and are not join keys.

For example
- d1 has columns ["key_id", "first_name", "age"]
- d2 has columns ["key_id", "last_name", "age"]

`pd.merge(d1, d2, on="key_id", suffixes=("_D1", "_D2"))`

The resulting dataframe will have the following columns
- ["key_id", "first_name", "last_name", "age_D1", "age_D2"]

Because age is present in both data frames and we must preserve both columns the solution is to rename both of them by appending a suffix string.

The default suffixes are ("_x", "_y") so you don't have to pass this paramater.

For no good reason other than to trouble you dear reader the `pd.DataFrame.join` method does not have a suffixes paramater but two paramaters:
- lsuffix which stands for left suffix
- rsuffix which stands for right suffix

The idea is still the same though.

#### Example 4. Full outer join in pandas.

Because this a full outer join all join keys are present (letters A to I).

In [0]:
pd.merge(df1, df2, how="outer", on=["name"])

name  age_x  age_y
0    A   22.0    NaN
1    B   18.0    NaN
2    C   46.0    NaN
3    D   81.0    NaN
4    G    NaN   10.0
5    H    NaN   20.0
6    I    NaN   30.0

#### Example 5. Left outer join in pandas.

Because this a left outer join only keys from the left dataframe are present (A, B, C, D).

In [0]:
pd.merge(df1, df2, how="left", on=["name"], suffixes=("_df1", "_df2"))

name  age_df1  age_df2
0    A       22      NaN
1    B       18      NaN
2    C       46      NaN
3    D       81      NaN

#### Example 1 of using the join function

Here we use a left outer join because we want a list of all bussiness irregardles if they have an entry in the hours table. If they don't have an entry all columns (Monday to Sunday) will be set to null which is the semantics of left join.

In [0]:
yelp_business.set_index("business_id", inplace=True)

yelp_hours.set_index("business_id", inplace=True)

yelp_business.join(yelp_hours)

name  \
business_id                                                                 
FYWN1wneV18bWNgQjJ2GNg                                 "Dental by Design"   
He-G7vWjzVUysIKrfNbPUQ                              "Stephen Szabo Salon"   
KQPW8lFf1y5BT2MxiSZ3QA                            "Western Motor Vehicle"   
8DShNS-LuFqpEWIp0HxijA                                 "Sports Authority"   
PfOCPjBrlQAnz__NXj9h_w                         "Brick House Tavern + Tap"   
o9eMRCWt5PkpLDE0gOPtcQ                                          "Messina"   
kCoE3jvEtg6UVz5SOD3GVw                                       "BDJ Realty"   
OD2hnuuTJI9uotcKycxg1A                                      "Soccer Zone"   
EsMcGiZaQuG1OOvL9iUFug                                 "Any Given Sundae"   
TGWhGNusxyMaA4kQVBNeew                            "Detailing Gone Mobile"   
XOSRcvtaKc_Q5H1SAzN20A                                "East Coast Coffee"   
Y0eMNa5C-YU1RQOZf9XvVA                           "CubeSmart Self Storage"   
xcgFnd-MwkZeO5G2HQ0gAQ                            "T & T Bakery and Cafe"   
NmZtoE3v8RdSJEczYbMT9g                             "Complete Dental Care"   
fNMVV_ZX7CJSDWQGdOM8Nw                       "Showmars Government Center"   
l09JfMeQ6ynYs5MCJtrcmQ                                   "Alize Catering"   
IQSlT5jGE6CCDhSG0zG3xg                                   "T & Y Nail Spa"   
b2I2DXtZVnpUMCXp1JON7A                          "Meineke Car Care Center"   
0FMKDOU8TJT1x87OKYGDTg                             "Senior's Barber Shop"   
Gu-xs3NIQTj3Mj2xYoN2aw                        "Maxim Bakery & Restaurant"   
lHYiCS-y8AFjUitv6MGpxg                                        "Starbucks"   
94KziT6DQ9XlBET3WzIv_w                                              "Fye"   
7YIy1tXOor9VCwvaSjuBHg  "TSA Checkpoint T-4 A - Phoenix Sky Harbor Int...   
PMH4oUa-bWELKogdtkWewg                                 "GoodLife Fitness"   
VSGcuYDV3q-AAZ9ZPq4fBQ                                      "Sportster's"   
1K4qrnfyzKzGgJPBEcJaNQ                           "Chula Taberna Mexicana"   
VBHEsoXQb2AQ76J9l8h1uQ                                "Alfredo's Jewelry"   
AtdXq_gu9NTE5rx4ct_dGg                                        "DAVIDsTEA"   
Dj0S-Oe4ytRJzMGUPgYUkw                                     "Panera Bread"   
gAy4LYpsScrj8POnCW6btQ                                       "Toast Cafe"   
...                                                                   ...   
z9BQubTnhhZd0iTJ-THbxg                                           "Isobar"   
axvE68Q_osdFijj1a21Omw                                   "Flair Cleaners"   
swjz4q8gI79Ndg4APuHEUA                   "Stonegate Real Estate Services"   
g0uFTFdKGarWEPb9gHlmag                    "Tanner Materials Tile & Stone"   
PfSNuUa53A-N5rY1kRshmA                              "Duquesne University"   
BhcpdT3W7YeyFeVAWPolkQ                             "Goodyear Endodontics"   
SvW3WsatQWvR8c1iwAD_QA                                 "Urban House Cafe"   
nGjEV4bn0DPk8bcb0C6Aig                      "Sweet Serendipity Bake Shop"   
pUhU5ohYv65g8B47dTXAKA                                        "Starbucks"   
sH9WsMj8sNTTSAUWv4UEEg                                     "Sprint Store"   
OMXqIZdvhDlrXlkpR34diQ                             "Swim Platforms, Inc."   
FxtrmM1a_0jcNnxiEF_Emg                                        "Badgarten"   
iR1CIWFZOlfndjXn9fHflQ                                 "Last Drop Tavern"   
R2oTFgwyurdx8fmZh7uAGg                                        "Hot Topic"   
6jzWUo0HAT3hNgBH-zHtYg                                           "Target"   
9ouC6BpmjFpLfHeQnLQqng                             "9 Dragons Fight Shop"   
JnhuORtEQOW8XkVXB3l2tQ                                              "CVS"   
vewqpBniDWKH4R05hxQwUQ                                      "Eos Fitness"   
yJH_gq99aEj8xtyBaAQH8Q                                       "Otto Onkel"   
n9a-3YhibkMDUEgncIivHg                                       "L'O

#### Example 2 of using the join function.

Using left outer join where the right dataframe is an empty dataframe you can add a lot of new columns to your existing dataframe by default filled with NaN.

Here we would like to add "address_street_number" and "address_street" to yelp_business.

This is not very useful here because we have little columns but this combined with `pd.DataFrame.fillna` method could make coding some algorithms an easier endeavour.

In [0]:
dummy_empty_df = pd.DataFrame(columns=["address_street_number", "address_street"])

yelp_business.join(dummy_empty_df)

name  \
business_id                                                                 
FYWN1wneV18bWNgQjJ2GNg                                 "Dental by Design"   
He-G7vWjzVUysIKrfNbPUQ                              "Stephen Szabo Salon"   
KQPW8lFf1y5BT2MxiSZ3QA                            "Western Motor Vehicle"   
8DShNS-LuFqpEWIp0HxijA                                 "Sports Authority"   
PfOCPjBrlQAnz__NXj9h_w                         "Brick House Tavern + Tap"   
o9eMRCWt5PkpLDE0gOPtcQ                                          "Messina"   
kCoE3jvEtg6UVz5SOD3GVw                                       "BDJ Realty"   
OD2hnuuTJI9uotcKycxg1A                                      "Soccer Zone"   
EsMcGiZaQuG1OOvL9iUFug                                 "Any Given Sundae"   
TGWhGNusxyMaA4kQVBNeew                            "Detailing Gone Mobile"   
XOSRcvtaKc_Q5H1SAzN20A                                "East Coast Coffee"   
Y0eMNa5C-YU1RQOZf9XvVA                           "CubeSmart Self Storage"   
xcgFnd-MwkZeO5G2HQ0gAQ                            "T & T Bakery and Cafe"   
NmZtoE3v8RdSJEczYbMT9g                             "Complete Dental Care"   
fNMVV_ZX7CJSDWQGdOM8Nw                       "Showmars Government Center"   
l09JfMeQ6ynYs5MCJtrcmQ                                   "Alize Catering"   
IQSlT5jGE6CCDhSG0zG3xg                                   "T & Y Nail Spa"   
b2I2DXtZVnpUMCXp1JON7A                          "Meineke Car Care Center"   
0FMKDOU8TJT1x87OKYGDTg                             "Senior's Barber Shop"   
Gu-xs3NIQTj3Mj2xYoN2aw                        "Maxim Bakery & Restaurant"   
lHYiCS-y8AFjUitv6MGpxg                                        "Starbucks"   
94KziT6DQ9XlBET3WzIv_w                                              "Fye"   
7YIy1tXOor9VCwvaSjuBHg  "TSA Checkpoint T-4 A - Phoenix Sky Harbor Int...   
PMH4oUa-bWELKogdtkWewg                                 "GoodLife Fitness"   
VSGcuYDV3q-AAZ9ZPq4fBQ                                      "Sportster's"   
1K4qrnfyzKzGgJPBEcJaNQ                           "Chula Taberna Mexicana"   
VBHEsoXQb2AQ76J9l8h1uQ                                "Alfredo's Jewelry"   
AtdXq_gu9NTE5rx4ct_dGg                                        "DAVIDsTEA"   
Dj0S-Oe4ytRJzMGUPgYUkw                                     "Panera Bread"   
gAy4LYpsScrj8POnCW6btQ                                       "Toast Cafe"   
...                                                                   ...   
z9BQubTnhhZd0iTJ-THbxg                                           "Isobar"   
axvE68Q_osdFijj1a21Omw                                   "Flair Cleaners"   
swjz4q8gI79Ndg4APuHEUA                   "Stonegate Real Estate Services"   
g0uFTFdKGarWEPb9gHlmag                    "Tanner Materials Tile & Stone"   
PfSNuUa53A-N5rY1kRshmA                              "Duquesne University"   
BhcpdT3W7YeyFeVAWPolkQ                             "Goodyear Endodontics"   
SvW3WsatQWvR8c1iwAD_QA                                 "Urban House Cafe"   
nGjEV4bn0DPk8bcb0C6Aig                      "Sweet Serendipity Bake Shop"   
pUhU5ohYv65g8B47dTXAKA                                        "Starbucks"   
sH9WsMj8sNTTSAUWv4UEEg                                     "Sprint Store"   
OMXqIZdvhDlrXlkpR34diQ                             "Swim Platforms, Inc."   
FxtrmM1a_0jcNnxiEF_Emg                                        "Badgarten"   
iR1CIWFZOlfndjXn9fHflQ                                 "Last Drop Tavern"   
R2oTFgwyurdx8fmZh7uAGg                                        "Hot Topic"   
6jzWUo0HAT3hNgBH-zHtYg                                           "Target"   
9ouC6BpmjFpLfHeQnLQqng                             "9 Dragons Fight Shop"   
JnhuORtEQOW8XkVXB3l2tQ                                              "CVS"   
vewqpBniDWKH4R05hxQwUQ                                      "Eos Fitness"   
yJH_gq99aEj8xtyBaAQH8Q                                       "Otto Onkel"   
n9a-3YhibkMDUEgncIivHg                                       "L'O

## Exercises

#### Exercise #1

Find all bussiness which are from 'AZ', 'PA', 'OH', 'BW', 'NV' using concatenation.

#### Exercise #2

Find all bussiness which are from 'AZ', 'PA', 'OH', 'BW', 'NV' using inner join.

Hint: You can use a temporary dataframe.

#### Exercise #3

Make one giant table from yelp_business, yelp_reviews, yelp_business_hours.

Hint: use the merge function

#### Exercise #4

Find the maximal review count from yelp_business and then using inner join find the business (or business) which have that review count.

#### Exercise #5

The yelp_reviews dataset has 14 rows where the stars column has a value of '?'.

We want to explore the businesses these reviews relate to.