In [23]:
#load dependencies
import numpy as np 
import pandas as pd 
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense

In [16]:
#Open Data Frame 
data = pd.read_excel('/content/Hospital Chrun.xlsx')

In [17]:
data.head()

RowNumber  Patient Medical Number  ... EstimatedSalary  Chrun
0          1                  199950  ...       101348.88      1
1          2                  199951  ...       112542.58      0
2          3                  199952  ...       113931.57      1
3          4                  199953  ...        93826.63      0
4          5                  199954  ...        79084.10      0

[5 rows x 14 columns]

In [20]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [21]:
# Encoding categorical data
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [22]:
# One Hot Encoding the "Demographics" column
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [29]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

In [37]:
>>> X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.2, random_state=0)

In [45]:
X_train = np.asarray(X_train).astype(np.float32)
y_train = np.asarray(y_train).astype(np.float32)
X_test = np.asarray(X_test).astype(np.float32)
y_test = np.asarray(y_test).astype(np.float32)

In [40]:
# Initializing the ANN
classifier=Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units=6,activation='relu'))

# Adding the second hidden layer
classifier.add(Dense(units=6,activation='relu'))

# Adding the input layer
classifier.add(Dense(units=1,activation='sigmoid'))


In [41]:
# Compiling the classifier
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
# Training the ANN on the Training set
classifier.fit(X_train, y_train, batch_size = 32, epochs = 20)

Epoch 1/20
250/250 [==============================] - 1s 1ms/step - loss: 205.3193 - accuracy: 0.6898
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 34.0594 - accuracy: 0.6787
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 19.2100 - accuracy: 0.6830
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 16.9939 - accuracy: 0.6812
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 13.6182 - accuracy: 0.6840
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 13.3365 - accuracy: 0.6808
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 12.6403 - accuracy: 0.6799
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 10.2677 - accuracy: 0.6871
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 9.1674 - accuracy: 0.6835
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 12.5891 - accura

In [46]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [47]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1547   48]
 [ 399    6]]


In [52]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [56]:
y_test

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0])

In [57]:
df_test = pd.DataFrame(y_test)
df_test

0
0   1
1   1
2   1
3   0
4   0
5   1
6   1
7   0
8   1
9   1
10  1
11  0
12  0
13  0
14  0
15  1
16  0
17  0
18  1
19  1
20  0
21  0
22  1
23  0
24  0

In [55]:
df_pred = pd.DataFrame(y_pred)
df_pred

0
0     False
1     False
2     False
3     False
4     False
...     ...
1995  False
1996  False
1997  False
1998  False
1999  False

[2000 rows x 1 columns]

In [62]:
df_test.to_excel(r'/content/test_data\File Name.xlsx', index = False)

In [63]:
df_pred.to_excel(r'/content/pred_data\File Name.xlsx', index = False)